#!/usr/bin/env python3
"""
S4 — SLO / Goodput analyzer for S3-C natural-generation results.

Reads existing S3-C Poisson load-point outputs and computes:
- request throughput
- SLO pass rate
- request goodput
- output-token goodput
- TTFT/ITL/E2E latency summaries
- running/waiting/KV metrics where available

Default SLO:
- TTFT <= 300 ms
- mean SSE content-event ITL <= 15 ms

Goodput definitions:
- request_goodput_req_s =
    successful requests satisfying BOTH SLOs / measured makespan
- output_goodput_tok_s =
    output tokens generated by SLO-passing requests / measured makespan

The analyzer intentionally uses natural-generation S3-C results as the
production-like workload. S3-D length-matched replay is not used here.

Expected layout:
results/s3/raw/poisson/coarse/lambda_*/requests.csv
results/s3/raw/poisson/coarse/lambda_*/run_metadata.json

By default, directories with names containing "cache_suspect" are ignored.

Run:
    python src/s4_analyze_goodput.py

Custom SLO:
    python src/s4_analyze_goodput.py \
        --ttft-slo-ms 300 \
        --itl-slo-ms 15
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

RAW_ROOT = PROJECT_ROOT / "results" / "s3" / "raw" / "poisson" / "coarse"
SUMMARY_DIR = PROJECT_ROOT / "results" / "s4" / "summary"
FIG_DIR = PROJECT_ROOT / "results" / "s4" / "figures"


def pct(values: Sequence[float], q: float) -> Optional[float]:
    xs = sorted(
        float(v)
        for v in values
        if v is not None and math.isfinite(float(v))
    )
    if not xs:
        return None
    if len(xs) == 1:
        return xs[0]
    k = (len(xs) - 1) * q
    lo = math.floor(k)
    hi = math.ceil(k)
    if lo == hi:
        return xs[lo]
    return xs[lo] * (hi - k) + xs[hi] * (k - lo)


def to_float(row: Dict[str, Any], key: str) -> Optional[float]:
    value = row.get(key)
    if value in (None, ""):
        return None
    try:
        f = float(value)
    except Exception:
        return None
    return f if math.isfinite(f) else None


def to_int(row: Dict[str, Any], key: str) -> Optional[int]:
    value = row.get(key)
    if value in (None, ""):
        return None
    try:
        return int(float(value))
    except Exception:
        return None


def load_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def run_label_from_path(path: Path) -> str:
    return path.name


def parse_configured_lambda(meta: Dict[str, Any]) -> float:
    return float(meta["configured_arrival_rate_req_s"])


def is_formal_candidate(path: Path) -> bool:
    name = path.name.lower()
    if "cache_suspect" in name:
        return False
    if not path.is_dir():
        return False
    return (
        (path / "requests.csv").exists()
        and (path / "run_metadata.json").exists()
    )


def discover_runs() -> List[Path]:
    if not RAW_ROOT.exists():
        raise FileNotFoundError(f"S3-C raw root not found: {RAW_ROOT}")

    candidates = [
        p for p in RAW_ROOT.iterdir()
        if is_formal_candidate(p)
    ]

    if not candidates:
        raise RuntimeError(
            f"No formal S3-C load-point directories found under {RAW_ROOT}"
        )

    parsed = []
    for p in candidates:
        meta = json.loads(
            (p / "run_metadata.json").read_text(encoding="utf-8")
        )
        parsed.append((parse_configured_lambda(meta), p))

    parsed.sort(key=lambda x: x[0])

    # Keep one run per configured lambda.
    # If duplicates exist, fail rather than silently choosing.
    seen = {}
    for lam, p in parsed:
        if lam in seen:
            raise RuntimeError(
                "Duplicate formal S3-C load points found for "
                f"lambda={lam}: {seen[lam]} and {p}. "
                "Rename archival/non-formal directories explicitly."
            )
        seen[lam] = p

    return [p for _, p in parsed]


def summarize_run(
    run_dir: Path,
    ttft_slo_ms: float,
    itl_slo_ms: float,
) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:

    meta = json.loads(
        (run_dir / "run_metadata.json").read_text(encoding="utf-8")
    )
    rows = load_csv(run_dir / "requests.csv")

    if meta.get("status") != "complete":
        raise RuntimeError(f"Run is not complete: {run_dir}")

    successful = [r for r in rows if r.get("status") == "ok"]

    if len(successful) != int(meta["successful_request_count"]):
        raise RuntimeError(
            f"Success-count mismatch in {run_dir}: "
            f"csv={len(successful)} meta={meta['successful_request_count']}"
        )

    makespan_s = float(meta["measured_makespan_s"])
    configured_lambda = float(meta["configured_arrival_rate_req_s"])
    realized_lambda = float(meta["realized_schedule_arrival_rate_req_s"])
    drain_s = float(meta["drain_after_last_scheduled_arrival_s"])

    ttfts = [
        to_float(r, "client_first_token_event_ttft_ms")
        for r in successful
    ]
    itls = [
        to_float(r, "mean_content_event_itl_ms")
        for r in successful
    ]
    e2es = [
        to_float(r, "client_e2e_ms")
        for r in successful
    ]

    request_eval_rows: List[Dict[str, Any]] = []

    pass_count = 0
    pass_output_tokens = 0
    ttft_pass_count = 0
    itl_pass_count = 0

    for r in successful:
        ttft = to_float(r, "client_first_token_event_ttft_ms")
        itl = to_float(r, "mean_content_event_itl_ms")
        output_tokens = to_int(r, "output_tokens") or 0

        ttft_pass = (
            ttft is not None
            and ttft <= ttft_slo_ms
        )

        # For one-token responses, there may be no ITL because there is no
        # interval between content events. Treat missing ITL as pass only when
        # output_tokens <= 1; otherwise mark fail/unknown conservatively.
        if itl is not None:
            itl_pass = itl <= itl_slo_ms
        else:
            itl_pass = output_tokens <= 1

        overall_pass = ttft_pass and itl_pass

        ttft_pass_count += int(ttft_pass)
        itl_pass_count += int(itl_pass)
        pass_count += int(overall_pass)

        if overall_pass:
            pass_output_tokens += output_tokens

        request_eval_rows.append({
            "configured_lambda_req_s": configured_lambda,
            "realized_lambda_req_s": realized_lambda,
            "request_id": r["request_id"],
            "workload_category": r["workload_category"],
            "ttft_ms": ttft,
            "mean_content_event_itl_ms": itl,
            "e2e_ms": to_float(r, "client_e2e_ms"),
            "output_tokens": output_tokens,
            "ttft_slo_pass": int(ttft_pass),
            "itl_slo_pass": int(itl_pass),
            "overall_slo_pass": int(overall_pass),
        })

    n = len(successful)
    total_output_tokens = sum(
        to_int(r, "output_tokens") or 0
        for r in successful
    )

    request_throughput = n / makespan_s
    output_throughput = total_output_tokens / makespan_s

    summary = {
        "run_label": run_label_from_path(run_dir),
        "configured_lambda_req_s": configured_lambda,
        "realized_lambda_req_s": realized_lambda,
        "request_count": len(rows),
        "successful_requests": n,
        "measured_makespan_s": makespan_s,
        "drain_s": drain_s,
        "max_client_inflight": meta.get("max_client_inflight"),
        "max_running": (
            meta.get("metrics_polling", {})
                .get("max_num_requests_running")
        ),
        "max_waiting": (
            meta.get("metrics_polling", {})
                .get("max_num_requests_waiting")
        ),
        "max_kv_cache_usage": (
            meta.get("metrics_polling", {})
                .get("max_kv_cache_usage_perc")
        ),
        "ttft_slo_ms": ttft_slo_ms,
        "itl_slo_ms": itl_slo_ms,
        "ttft_slo_pass_count": ttft_pass_count,
        "itl_slo_pass_count": itl_pass_count,
        "overall_slo_pass_count": pass_count,
        "ttft_slo_pass_rate": ttft_pass_count / n if n else None,
        "itl_slo_pass_rate": itl_pass_count / n if n else None,
        "overall_slo_pass_rate": pass_count / n if n else None,
        "request_throughput_req_s": request_throughput,
        "request_goodput_req_s": pass_count / makespan_s,
        "total_output_tokens": total_output_tokens,
        "slo_passing_output_tokens": pass_output_tokens,
        "output_throughput_tok_s": output_throughput,
        "output_goodput_tok_s": pass_output_tokens / makespan_s,
        "goodput_efficiency_request": (
            (pass_count / makespan_s) / request_throughput
            if request_throughput > 0
            else None
        ),
        "goodput_efficiency_output": (
            (pass_output_tokens / makespan_s) / output_throughput
            if output_throughput > 0
            else None
        ),
        "ttft_p50_ms": pct(ttfts, 0.50),
        "ttft_p95_ms": pct(ttfts, 0.95),
        "ttft_p99_ms": pct(ttfts, 0.99),
        "itl_p50_ms": pct(itls, 0.50),
        "itl_p95_ms": pct(itls, 0.95),
        "itl_p99_ms": pct(itls, 0.99),
        "e2e_p50_ms": pct(e2es, 0.50),
        "e2e_p95_ms": pct(e2es, 0.95),
        "e2e_p99_ms": pct(e2es, 0.99),
    }

    return summary, request_eval_rows


def write_csv(
    path: Path,
    fields: Sequence[str],
    rows: Sequence[Dict[str, Any]],
) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=list(fields),
            extrasaction="ignore",
        )
        writer.writeheader()
        writer.writerows(rows)


def save_line(
    xs: Sequence[float],
    ys: Sequence[float],
    xlabel: str,
    ylabel: str,
    title: str,
    path: Path,
) -> None:
    plt.figure(figsize=(8, 5))
    plt.plot(xs, ys, marker="o")
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(path, dpi=180)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--ttft-slo-ms",
        type=float,
        default=300.0,
    )
    parser.add_argument(
        "--itl-slo-ms",
        type=float,
        default=15.0,
    )
    args = parser.parse_args()

    if args.ttft_slo_ms <= 0:
        raise ValueError("--ttft-slo-ms must be > 0")
    if args.itl_slo_ms <= 0:
        raise ValueError("--itl-slo-ms must be > 0")

    run_dirs = discover_runs()

    SUMMARY_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    summaries: List[Dict[str, Any]] = []
    eval_rows: List[Dict[str, Any]] = []

    for run_dir in run_dirs:
        summary, req_rows = summarize_run(
            run_dir,
            ttft_slo_ms=args.ttft_slo_ms,
            itl_slo_ms=args.itl_slo_ms,
        )
        summaries.append(summary)
        eval_rows.extend(req_rows)

    summaries.sort(key=lambda r: float(r["configured_lambda_req_s"]))

    summary_fields = list(summaries[0].keys())
    request_fields = [
        "configured_lambda_req_s",
        "realized_lambda_req_s",
        "request_id",
        "workload_category",
        "ttft_ms",
        "mean_content_event_itl_ms",
        "e2e_ms",
        "output_tokens",
        "ttft_slo_pass",
        "itl_slo_pass",
        "overall_slo_pass",
    ]

    summary_csv = SUMMARY_DIR / "s4_goodput_summary.csv"
    requests_csv = SUMMARY_DIR / "s4_request_slo_audit.csv"

    write_csv(summary_csv, summary_fields, summaries)
    write_csv(requests_csv, request_fields, eval_rows)

    xs = [float(r["realized_lambda_req_s"]) for r in summaries]

    save_line(
        xs,
        [float(r["request_throughput_req_s"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "Request throughput (requests/s)",
        "S4 Request Throughput vs Arrival Rate",
        FIG_DIR / "01_request_throughput_vs_arrival_rate.png",
    )

    save_line(
        xs,
        [float(r["request_goodput_req_s"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "Goodput (SLO-passing requests/s)",
        "S4 Request Goodput vs Arrival Rate",
        FIG_DIR / "02_request_goodput_vs_arrival_rate.png",
    )

    save_line(
        xs,
        [100.0 * float(r["overall_slo_pass_rate"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "SLO pass rate (%)",
        "S4 SLO Pass Rate vs Arrival Rate",
        FIG_DIR / "03_slo_pass_rate_vs_arrival_rate.png",
    )

    save_line(
        xs,
        [float(r["output_throughput_tok_s"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "Output throughput (tokens/s)",
        "S4 Output Throughput vs Arrival Rate",
        FIG_DIR / "04_output_throughput_vs_arrival_rate.png",
    )

    save_line(
        xs,
        [float(r["output_goodput_tok_s"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "SLO-passing output tokens/s",
        "S4 Output-Token Goodput vs Arrival Rate",
        FIG_DIR / "05_output_goodput_vs_arrival_rate.png",
    )

    save_line(
        xs,
        [float(r["ttft_p95_ms"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "P95 TTFT (ms)",
        "S4 P95 TTFT vs Arrival Rate",
        FIG_DIR / "06_p95_ttft_vs_arrival_rate.png",
    )

    save_line(
        xs,
        [float(r["itl_p95_ms"]) for r in summaries],
        "Realized arrival rate (requests/s)",
        "P95 mean content-event ITL (ms)",
        "S4 P95 ITL vs Arrival Rate",
        FIG_DIR / "07_p95_itl_vs_arrival_rate.png",
    )

    report = {
        "phase": "S4",
        "definition": {
            "ttft_slo_ms": args.ttft_slo_ms,
            "itl_slo_ms": args.itl_slo_ms,
            "overall_request_pass": (
                "TTFT <= threshold AND mean content-event ITL <= threshold"
            ),
            "request_goodput_req_s": (
                "SLO-passing successful requests / measured makespan"
            ),
            "output_goodput_tok_s": (
                "output tokens from SLO-passing requests / measured makespan"
            ),
            "important_note": (
                "This is application/SSE-level goodput, not pure GPU-kernel "
                "goodput. Natural-generation S3-C outputs are intentionally used."
            ),
        },
        "runs": summaries,
    }

    report_path = SUMMARY_DIR / "s4_goodput_summary.json"
    report_path.write_text(
        json.dumps(report, indent=2),
        encoding="utf-8",
    )

    print("=" * 100)
    print("S4 — SLO / GOODPUT ANALYSIS COMPLETE")
    print("=" * 100)
    print(
        f"SLO: TTFT <= {args.ttft_slo_ms:.0f} ms AND "
        f"mean content-event ITL <= {args.itl_slo_ms:.1f} ms"
    )
    print()
    print(
        f"{'cfg λ':>7} {'real λ':>8} {'pass%':>8} "
        f"{'req/s':>8} {'goodput':>9} "
        f"{'out tok/s':>10} {'out good':>10} "
        f"{'P95 TTFT':>10} {'P95 ITL':>9}"
    )
    print("-" * 100)

    for r in summaries:
        print(
            f"{float(r['configured_lambda_req_s']):7.2f} "
            f"{float(r['realized_lambda_req_s']):8.3f} "
            f"{100*float(r['overall_slo_pass_rate']):8.2f} "
            f"{float(r['request_throughput_req_s']):8.3f} "
            f"{float(r['request_goodput_req_s']):9.3f} "
            f"{float(r['output_throughput_tok_s']):10.1f} "
            f"{float(r['output_goodput_tok_s']):10.1f} "
            f"{float(r['ttft_p95_ms']):10.1f} "
            f"{float(r['itl_p95_ms']):9.2f}"
        )

    best = max(
        summaries,
        key=lambda r: float(r["request_goodput_req_s"])
    )

    print()
    print(
        "Highest request goodput among analyzed points: "
        f"configured λ={float(best['configured_lambda_req_s']):.2f}, "
        f"realized λ={float(best['realized_lambda_req_s']):.3f}, "
        f"goodput={float(best['request_goodput_req_s']):.3f} req/s, "
        f"SLO pass={100*float(best['overall_slo_pass_rate']):.2f}%"
    )
    print()
    print(f"Summary CSV:  {summary_csv}")
    print(f"Request audit:{requests_csv}")
    print(f"Summary JSON: {report_path}")
    print(f"Figures:      {FIG_DIR}")


if __name__ == "__main__":
    main()
